added the toggle command

diff --git a/qidled b/qidled
--- a/qidled
+++ b/qidled
@@ -128,6 +128,9 @@ restart
 	Restart the qidle daemon. Configuration changes always require a daemon restart
 	to become effective.
 
+toggle
+	Stops the daemon, if running and starts it, if stopped. Useful to bind to a hotkey.
+
 status
 	Check whether a qidle daemon is running in the background. Sets a zero exit code,
 	if the daemon is running and a non-zero exit code otherwise.
@@ -864,6 +867,18 @@ user="$(whoami)" || { B_ERR="Failed to obtain the current user." ; B_E }
 [[ "$user" != "root" ]] || { B_ERR="This script must have access to the X server, but the user $user does not have access to it." ; B_E }
 }
 
+#toggle
+#See usage().
+function toggle {
+if b_daemon_status "$DID" > /dev/null ; then
+	#NOTE: We silently ignore passed options (these are only relevant for starting).
+	"${BASH_SOURCE[0]}" "stop"
+else
+	local opts="$(b_args_getAllOptions)"
+	"${BASH_SOURCE[0]}" $opts "start"
+fi
+}
+
 b_deps "date" "qvm-ls" "logger" "notify-send" "xssstate" "xprop" "qvm-unpause" "qvm-run" "sort"
 b_args_parse "$@"
 [ $(b_args_getCount) -eq 1 ] || usage
@@ -896,6 +911,10 @@ case "$(b_args_get 0)" in
 		b_args_assertOptions "-v" "-q"
 		b_daemon_stop "$DID" "SIGUSR2" 15
 		b_daemon_start "$DID"
+		;;
+	"toggle")
+		toggle
+		exit $?
 		;;
 	"status")
 		b_args_assertOptions
